// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/api/etoro/chart.ts";
import * as $3 from "./routes/api/etoro/discover.ts";
import * as $4 from "./routes/api/etoro/portfolio.ts";
import * as $5 from "./routes/api/etoro/stats.ts";
import * as $6 from "./routes/api/joke.ts";
import * as $7 from "./routes/api/v1/file/[filename].ts";
import * as $8 from "./routes/api/v1/file/_middleware.ts";
import * as $9 from "./routes/greet/[name].tsx";
import * as $10 from "./routes/index.tsx";
import * as $$0 from "./islands/Chart.tsx";
import * as $$1 from "./islands/Counter.tsx";
import * as $$2 from "./islands/Discover.tsx";
import * as $$3 from "./islands/Portfolio.tsx";
import * as $$4 from "./islands/Stats.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/api/etoro/chart.ts": $2,
    "./routes/api/etoro/discover.ts": $3,
    "./routes/api/etoro/portfolio.ts": $4,
    "./routes/api/etoro/stats.ts": $5,
    "./routes/api/joke.ts": $6,
    "./routes/api/v1/file/[filename].ts": $7,
    "./routes/api/v1/file/_middleware.ts": $8,
    "./routes/greet/[name].tsx": $9,
    "./routes/index.tsx": $10,
  },
  islands: {
    "./islands/Chart.tsx": $$0,
    "./islands/Counter.tsx": $$1,
    "./islands/Discover.tsx": $$2,
    "./islands/Portfolio.tsx": $$3,
    "./islands/Stats.tsx": $$4,
  },
  baseUrl: import.meta.url,
};

export default manifest;
